# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - main

env:
  NODE_VERSION: lts/*

jobs:
  build-lint-ts:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.0.0

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: 🏗 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🚀 Build Typescript
        run: yarn build
